// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.25_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.25_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.1_@parcel+watcher@2.5.1_@types+node@22.19.1_@vue+compiler-sfc@3.5.25_cac@6.7.1_a20ce2f364265bbb7e7ba0deead3b06a/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../app/plugins/00.svg-icons.client")> &
  InjectionType<typeof import("../../app/plugins/01.di-container.client")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
