openapi: 3.0.3
info:
  title: Matchmaking API
  description: API for online matchmaking in Hanafuda Koi-Koi
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /matchmaking/enter:
    post:
      summary: Enter matchmaking queue
      description: |
        Adds the authenticated player to the matchmaking queue for the specified room type.
        Returns an entry ID used to track matchmaking status.

        **Error Cases**:
        - 400: Player already in queue
        - 401: Not authenticated
        - 422: Invalid room type
      operationId: enterMatchmaking
      tags:
        - Matchmaking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnterMatchmakingRequest'
      responses:
        '200':
          description: Successfully entered matchmaking queue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnterMatchmakingResponse'
        '400':
          description: Already in matchmaking queue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchmakingError'
              example:
                success: false
                error_code: ALREADY_IN_QUEUE
                message: You are already in the matchmaking queue
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchmakingError'
        '422':
          description: Invalid room type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchmakingError'

  /matchmaking/cancel:
    post:
      summary: Cancel matchmaking
      description: |
        Removes the player from the matchmaking queue.
        If player was about to be matched, the other player continues searching.
      operationId: cancelMatchmaking
      tags:
        - Matchmaking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelMatchmakingRequest'
      responses:
        '200':
          description: Successfully cancelled matchmaking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelMatchmakingResponse'
        '400':
          description: Not in matchmaking queue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchmakingError'
              example:
                success: false
                error_code: NOT_IN_QUEUE
                message: You are not in the matchmaking queue
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchmakingError'

  /matchmaking/status:
    get:
      summary: Subscribe to matchmaking status (SSE)
      description: |
        Server-Sent Events endpoint for receiving real-time matchmaking status updates.

        **Event Types**:
        - `MatchmakingStatus`: Status update (SEARCHING, LOW_AVAILABILITY)
        - `MatchFound`: Match found, includes game_id for navigation
        - `MatchmakingCancelled`: Matchmaking was cancelled
        - `MatchmakingError`: Error occurred

        **Timeline**:
        - 0-10s: SEARCHING status
        - 10-15s: LOW_AVAILABILITY status
        - 15s+: MatchFound with bot opponent
      operationId: getMatchmakingStatus
      tags:
        - Matchmaking
      parameters:
        - name: entry_id
          in: query
          required: true
          description: Entry ID returned from /matchmaking/enter
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: SSE stream of matchmaking events
          content:
            text/event-stream:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/MatchmakingStatusEvent'
                  - $ref: '#/components/schemas/MatchFoundEvent'
                  - $ref: '#/components/schemas/MatchmakingCancelledEvent'
                  - $ref: '#/components/schemas/MatchmakingErrorEvent'
        '400':
          description: Invalid entry ID
        '401':
          description: Not authenticated
        '404':
          description: Entry not found or expired

components:
  schemas:
    # Request/Response Schemas
    EnterMatchmakingRequest:
      type: object
      required:
        - room_type
      properties:
        room_type:
          $ref: '#/components/schemas/RoomTypeId'

    EnterMatchmakingResponse:
      type: object
      required:
        - success
        - entry_id
        - message
      properties:
        success:
          type: boolean
          example: true
        entry_id:
          type: string
          format: uuid
          description: Unique identifier for this matchmaking entry
        message:
          type: string
          example: Searching for opponent...

    CancelMatchmakingRequest:
      type: object
      required:
        - entry_id
      properties:
        entry_id:
          type: string
          format: uuid
          description: Entry ID to cancel

    CancelMatchmakingResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Matchmaking cancelled

    MatchmakingError:
      type: object
      required:
        - success
        - error_code
        - message
      properties:
        success:
          type: boolean
          example: false
        error_code:
          type: string
          enum:
            - ALREADY_IN_QUEUE
            - NOT_IN_QUEUE
            - INVALID_ROOM_TYPE
            - ENTRY_NOT_FOUND
            - UNAUTHORIZED
            - INTERNAL_ERROR
        message:
          type: string

    # SSE Event Schemas
    MatchmakingStatusEvent:
      type: object
      required:
        - event_type
        - entry_id
        - status
        - message
        - elapsed_seconds
      properties:
        event_type:
          type: string
          enum: [MatchmakingStatus]
        entry_id:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - SEARCHING
            - LOW_AVAILABILITY
        message:
          type: string
          description: Human-readable status message (English)
          example: Searching for opponent...
        elapsed_seconds:
          type: integer
          description: Seconds since entering queue
          example: 5

    MatchFoundEvent:
      type: object
      required:
        - event_type
        - game_id
        - opponent_name
        - is_bot
      properties:
        event_type:
          type: string
          enum: [MatchFound]
        game_id:
          type: string
          format: uuid
          description: Game ID to connect to via /api/v1/games/connect
        opponent_name:
          type: string
          description: Opponent's display name
          example: Player123
        is_bot:
          type: boolean
          description: Whether opponent is a bot (computer)
          example: false

    MatchmakingCancelledEvent:
      type: object
      required:
        - event_type
      properties:
        event_type:
          type: string
          enum: [MatchmakingCancelled]

    MatchmakingErrorEvent:
      type: object
      required:
        - event_type
        - error_code
        - message
      properties:
        event_type:
          type: string
          enum: [MatchmakingError]
        error_code:
          type: string
        message:
          type: string

    # Shared Types
    RoomTypeId:
      type: string
      enum:
        - QUICK
        - STANDARD
        - MARATHON
      description: Room type identifier

  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: session
      description: Session cookie from Identity BC

security:
  - sessionAuth: []

tags:
  - name: Matchmaking
    description: Online matchmaking operations
